#!/usr/bin/env bash
# Copyright (C) 2026 CachyOS
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Overwrite zram-generator configuration when vswap is available
value="$(grep -P -o '(?(?=.*\s)\s+|^)(vswap=\K(on|off))(?!u(?(?=\s+).*|$))' /proc/cmdline)"
if (zgrep -q '^CONFIG_VSWAP_DEFAULT_ON=y$' /proc/config.gz && [[ "$value" != "off" ]]) || [[ "$value" == "on" ]]; then
    ln -s /dev/null /run/systemd/zram-generator.conf
fi
